export const DISHES = [
  {
    id: 1,
    name: "Tahrir Koshary",
    desc: " ",
    price: 35,
    category: "main",
    img: "/images/a.jpg",
  },
  {
    id: 2,
    name: "Top Tahrir Koshary",
    desc: "",
    price: 40,
    category: "main",
    img: "/images/b.jpg",
  },
  {
    id: 3,
    name: "Large Tahrir Koshary",
    desc: "     ",
    price: 50,
    category: "main",
    img: "/images/c.jpg",
  },
  {
    id: 4,
    name: " King Tahrir Koshary",
    desc: "",
    price: 55,
    category: "main",
    img: "/images/d.jpg",
  },
  {
    id: 5,
    name: "Family Tahrir Koshary",
    desc: "",
    price: 60,
    category: "main",
    img: "/images/family.jpg",
  },
  {
    id: 6,
    name: "Mega Tahrir ",
    desc: "",
    price: 70,
    category: "main",
    img: "/images/family2.jpg",
  },
];
export const Additions = [
  {
    id: 1,
    name: "Fried Onion",
    desc: " ",
    price: 10,
    category: "main",
    img: "/images/1.jpg",
  },
  {
    id: 2,
    name: "Garlic Sauce ",
    desc: "",
    price: 12,
    category: "main",
    img: "/images/2.jpg",
  },
  {
    id: 3,
    name: "Hot sause ",
    desc: "     ",
    price: 15,
    category: "main",
    img: "/images/3.jpg",
  },
  {
    id: 4,
    name: " Tomato Sauce",
    desc: "",
    price: 20,
    category: "main",
    img: "/images/3-1.jpg",
  },
  {
    id: 5,
    name: "Chickpeas",
    desc: "",
    price: 20,
    category: "main",
    img: "/images/4.jpg",
  },
  {
    id: 6,
    name: "Lentils ",
    desc: "",
    price: 25,
    category: "main",
    img: "/images/8.png",
  },
];
export const Drinks = [
  {
    id: 1,
    name: "Miranda Apple",
    desc: " ",
    price: 20,
    category: "main",
    img: "/images/5.jpg",
  },
  {
    id: 2,
    name: "Mirinda Orange ",
    desc: "",
    price: 120,
    category: "main",
    img: "/images/6.jpg",
  },
  {
    id: 3,
    name: "7 UP Diet",
    desc: "     ",
    price: 20,
    category: "main",
    img: "/images/7.jpg",
  },
  {
    id: 4,
    name: " Pepsi Diet",
    desc: "",
    price: 20,
    category: "main",
    img: "/images/10.jpg",
  },
  {
    id: 5,
    name: "Pepsi",
    desc: "",
    price: 20,
    category: "main",
    img: "/images/11.jpg",
  },
  {
    id: 6,
    name: "Mineral Water ",
    desc: "",
    price: 10,
    category: "main",
    img: "/images/9.jpg",
  },
];
