export const DISHES = [
  {
    id: 1,
    name: "كشري التحرير",
    desc: "طبق مصري كلاسيكي من الأرز والعدس والمكرونة والحمص مغطى بصلصة الطماطم الحارة والبصل المقلي المقرمش.",
    price: 35,
    category: "main",
    img: "/images/a.jpg",
  },
  {
    id: 2,
    name: "كشري التحرير المميز",
    desc: "النسخة المميزة من كشري التحرير الخاص بنا مع حصص إضافية من العدس وطبقة سخية من البصل المكرمل.",
    price: 40,
    category: "main",
    img: "/images/b.jpg",
  },
  {
    id: 3,
    name: "كشري التحرير الكبير",
    desc: "حصتنا الكبيرة من الكشري التقليدي، مثالية للمشاركة أو عندما تكون جائعاً جداً.",
    price: 50,
    category: "main",
    img: "/images/c.jpg",
  },
  {
    id: 4,
    name: "كشري التحرير الملكي",
    desc: "تجربة الكشري النهائية مع حصص مزدوجة وإضافات مميزة للذواقة الحقيقي.",
    price: 55,
    category: "main",
    img: "/images/d.jpg",
  },
  {
    id: 5,
    name: "كشري التحرير العائلي",
    desc: "حصة كبيرة بحجم العائلة من كشري التحرير الأصيل، مثالية للتجمعات العائلية.",
    price: 60,
    category: "main",
    img: "/images/family.jpg",
  },
  {
    id: 6,
    name: "كشري التحرير العملاق",
    desc: "أكبر حصة لدينا من الكشري، محملة بجميع المكونات التقليدية لأقصى درجات الرضا.",
    price: 70,
    category: "main",
    img: "/images/family2.jpg",
  },
];
export const Additions = [
  {
    id: 7,
    name: "بصل مقلي",
    desc: " ",
    price: 10,
    category: "main",
    img: "/images/1.jpg",
  },
  {
    id: 8,
    name: "صلصة الثوم",
    desc: "",
    price: 12,
    category: "main",
    img: "/images/2.jpg",
  },
  {
    id: 9,
    name: "صلصة حارة",
    desc: "     ",
    price: 15,
    category: "main",
    img: "/images/3.jpg",
  },
  {
    id: 10,
    name: "صلصة الطماطم",
    desc: "",
    price: 20,
    category: "main",
    img: "/images/3-1.jpg",
  },
  {
    id: 11,
    name: "حمص",
    desc: "",
    price: 20,
    category: "main",
    img: "/images/4.jpg",
  },
  {
    id: 12,
    name: "عدس",
    desc: "",
    price: 25,
    category: "main",
    img: "/images/8.png",
  },
];
export const Drinks = [
  {
    id: 13,
    name: "ميراندا تفاح",
    desc: " ",
    price: 20,
    category: "main",
    img: "/images/5.jpg",
  },
  {
    id: 14,
    name: "ميراندا برتقال",
    desc: "",
    price: 120,
    category: "main",
    img: "/images/6.jpg",
  },
  {
    id: 15,
    name: "7 أب دايت",
    desc: "     ",
    price: 20,
    category: "main",
    img: "/images/7.jpg",
  },
  {
    id: 16,
    name: "بيبسي دايت",
    desc: "",
    price: 20,
    category: "main",
    img: "/images/10.jpg",
  },
  {
    id: 17,
    name: "بيبسي",
    desc: "",
    price: 20,
    category: "main",
    img: "/images/11.jpg",
  },
  {
    id: 18,
    name: "ماء معدني",
    desc: "",
    price: 10,
    category: "main",
    img: "/images/9.jpg",
  },
];

export const Desserts = [
  {
    id: 19,
    name: "  أم علي ساده",
    desc: " ",
    price: 25,
    category: "main",
    img: "/images/Om-Ali-Dessert.jpg",
  },
  {
    id: 20,
    name: "أم علي مكسرات",
    desc: " ",
    price: 25,
    category: "main",
    img: "/images/omALi.jpg",
  },
  {
    id: 21,
    name: " أم علي بالشوكولاتة",
    desc: " ",
    price: 25,
    category: "main",
    img: "/images/Desserts3.webp",
  },
  {
    id: 22,
    name: "أرز باللبن",
    desc: " ",
    price: 25,
    category: "main",
    img: "/images/desert2.jpg",
  },
  {
    id: 23,
    name: "بودينج",
    desc: " ",
    price: 25,
    category: "main",
    img: "/images/desert2.jpg",
  },
];
